var CONFIG = {};

CONFIG.BLOG_TITLE = 'Blog Title';
CONFIG.NAV_TITLE = 'Nav Title';

CONFIG.SHOW_SIDEBAR = true;
CONFIG.NUM_POSTS_IN_SIDEBAR = 5;
CONFIG.NUM_POSTS_PER_PAGE = 4;
CONFIG.ENABLE_ANIMATIONS = true;

CONFIG.USE_DISQUS = true;
CONFIG.DISQUS_SHORT_NAME = 'yangshun';
CONFIG.SITE_DOMAIN = 'yangshun.im/luna/';